version: '3'

services:
  composer:
    image: composer
    volumes:
      - .:/app
      - ~/.composer:/tmp

  php:
    image: graze/php-alpine:5-test
    volumes:
      - .:/srv
    working_dir: /srv
